### ISSUE TITLE
Question about your CL side font function

### ISSUE THREAD

**Issue by TheObtey** [MaaxIT/gcreator#1]
Hello, i've been using your script for two weeks but I still don't understand how am I supposed to use it.
Am I supposed to use sName as the font name ? Or is it "sName" ? In the two case I got a error so can you help me about this please. 
Cheers !

**Comment by wasied** [comment]
Hello,

sName is an internal variable that is not meant to be used outside of the Font function.
The function "Addon:Font" is returning the name of the font you can use to draw your texts and stuff.

Here is an example:
`draw.SimpleText("Hello', Addon:Font(24), 0, 0, color_white)`

I'll close this issue, please open a new one if you have any further issue.
Thanks, Wasied.
